name: AOSPA ROM Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      BUILD_USER: github
      BUILD_HOST: github-actions
      CCACHE_DIR: /tmp/ccache

    steps:
      - name: Checkout (for local files/scripts)
        uses: actions/checkout@v4

      - name: Setup Swap
        run: |
          sudo fallocate -l 16G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip python3

      - name: Install repo tool
        run: |
          sudo curl -o /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+x /usr/local/bin/repo

      - name: Initialize Repo and Local Manifest
        run: |
          repo init -u https://github.com/AOSPA/manifest.git -b uvite --depth=1
          git clone --depth=1 -b AOSPA https://github.com/Jayzee-Zee/Local-Manifest.git .repo/local_manifests

      - name: Sync Source
        run: |
          repo sync -c --no-tags --no-clone-bundle -j$(nproc --all)

      - name: Setup CCache
        run: |
          export USE_CCACHE=1
          ccache -M 20G

      - name: Build ROM
        run: |
          source build/envsetup.sh
          lunch aospa_earth-userdebug
          make -j$(nproc --all) bacon

      - name: Upload ROM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aospa-rom
          path: out/target/product/earth/*.zip
